# Site settings
title: I Am Finite
email: resercmichael@gmail.com
url: https://i-am-finite.github.io
description: "I’m a Full-Stack Developer, Music Producer, and Visual Artist, merging technology, music, and timeless art forms. From building dynamic web applications to creating audio and visual artistry, I combine technical precision with creative passion. Here you can explore my projects, artistic works, and music!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: I Am Finite

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Twitter
    url: https://x.com/I_Am_Finite
  - title: GitHub
    url: https://github.com/I-Am-Finite
  - title: LinkedIn
    url: https://www.linkedin.com/in/michaelreser/
  - title: Instagram
    url: https://www.instagram.com/i_am_finite/


# Build settings
markdown: kramdown
permalink: pretty
