# Site settings
title: Pushing Forward
email: resercmichael@gmail.com
url: https://i-am-finite.github.io
description: "Merging technology, music, and timeless art forms. From building dynamic web applications to creating audio and visual artistry, I combine technical precision with creative passion. Here you can explore my projects, artistic works, and music!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Michael Reser

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/I-Am-Finite
  - title: linkedin
    url: https://www.linkedin.com/in/michaelreser/
  - title: twitter
    url: https://x.com/I_Am_Finite
  - title: instagram
    url: https://www.instagram.com/i_am_finite/


# Build settings
markdown: kramdown
permalink: pretty
