# Site settings
title: I Am Finite
email: resercmichael@gmail.com
url: https://i-am-finite.github.io
description: "I’m a Full-Stack Developer, Music Producer, DJ, and Artist, merging technology, music, and timeless art forms. From building dynamic web applications to creating audio and visual art, I combine technical precision with creative passion. Here you can explore my projects, artistic works, and music!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: I Am Finite

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
